apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.appname }}-admin-service
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ $.Values.appname }}-{{ $.Values.environment }}-admin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000