apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ramselvin-saas-auth-ingress
  namespace: ramselvin-saas
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: auth.ramselvin.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ramselvin-saas-auth-service
            port:
              number: 80

