apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.appname }}-auth-service
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ $.Values.appname }}-{{ $.Values.environment }}-auth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000