apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.appname }}-ingress
  namespace: {{ $.Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ramselvin.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ $.Values.appname }}-frontend-service
            port:
              number: 80
